stn=1
server=1
rest=1
listen=1
printtoconsole=1

rpcuser=bitfs
rpcpassword=bitfs
rpcbind=0.0.0.0
rpcport=18332
rpcallowip=0.0.0.0/0

txindex=1

excessiveblocksize=10000000000
maxstackmemoryusageconsensus=100000000
