regtest=1
server=1
rest=1
listen=1
printtoconsole=1
dnsseed=0
upnp=0
listenonion=0

rpcuser=bitfs
rpcpassword=bitfs
rpcbind=0.0.0.0
rpcport=18332
rpcallowip=0.0.0.0/0

port=18444
txindex=1
genesisactivationheight=1

excessiveblocksize=2000000000
maxstackmemoryusageconsensus=100000000

maxmempool=512
minminingtxfee=0.00000050
