services:
  bsv-node:
    image: bitcoinsv/bitcoin-sv:1.0.11
    container_name: bitfs-regtest
    ports:
      - "18332:18332"
      - "18444:18444"
    volumes:
      - ./bitcoin.conf:/data/bitcoin.conf
      - bsv-data:/data
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "-regtest", "getinfo"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  bsv-data:
