services:
  bsv-node:
    image: bitcoinsv/bitcoin-sv:1.0.11
    container_name: bitfs-stn
    ports:
      - "18334:18332"
      - "18336:9333"
    volumes:
      - ./bitcoin-stn.conf:/data/bitcoin.conf
      - bsv-stn-data:/data
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "-stn", "getinfo"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  bsv-stn-data:
