// Copyright (c) 2024 The Metanet developers
// Use of this source code is governed by the Open BSV License v5
// that can be found in the LICENSE file.

// Package config provides configuration management for the Metanet Node.
// Configuration uses a simple key=value file format with # comments.
package config

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Config holds the Metanet Node configuration.
type Config struct {
	// DataDir is the root data directory for the node.
	// Default: ~/.metanet
	DataDir string

	// ListenAddr is the address for overlay network connections.
	// Default: :8334
	ListenAddr string

	// RPCAddr is the address for the RPC API.
	// Default: :8335
	RPCAddr string

	// Network is the chain network: "mainnet" or "testnet".
	// Default: mainnet
	Network string

	// MaxPeers is the maximum number of connected peers.
	// Default: 50
	MaxPeers int

	// MineEnabled controls whether merged mining is active.
	// Default: false
	MineEnabled bool

	// LogLevel controls the logging verbosity.
	// Valid values: "debug", "info", "warn", "error".
	// Default: info
	LogLevel string

	// LogFile is the path to the log file. Empty means stdout.
	// Default: "" (stdout)
	LogFile string
}

// DefaultDataDir returns the default data directory path (~/.metanet).
func DefaultDataDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ".metanet"
	}
	return filepath.Join(home, ".metanet")
}

// DefaultConfig returns a Config populated with sensible defaults.
func DefaultConfig() Config {
	return Config{
		DataDir:     DefaultDataDir(),
		ListenAddr:  ":8334",
		RPCAddr:     ":8335",
		Network:     "mainnet",
		MaxPeers:    50,
		MineEnabled: false,
		LogLevel:    "info",
		LogFile:     "",
	}
}

// LoadConfig reads a configuration file at the given path and returns
// a Config. The file uses simple key=value format (one per line) with
// # comments and blank lines ignored.
//
// Any keys not present in the file retain their default values.
func LoadConfig(path string) (Config, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return Config{}, ErrConfigNotFound
		}
		return Config{}, fmt.Errorf("config: open %s: %w", path, err)
	}
	defer func() { _ = f.Close() }()

	cfg := DefaultConfig()
	if err := parseConfig(f, &cfg); err != nil {
		return Config{}, err
	}
	return cfg, nil
}

// parseConfig reads key=value pairs from r into cfg.
func parseConfig(r io.Reader, cfg *Config) error {
	scanner := bufio.NewScanner(r)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())

		// Skip blank lines and comments.
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		key, value, ok := parseKeyValue(line)
		if !ok {
			return fmt.Errorf("%w: line %d: %q", ErrInvalidConfigLine, lineNum, line)
		}

		if err := setConfigField(cfg, key, value); err != nil {
			return fmt.Errorf("config: line %d: %w", lineNum, err)
		}
	}
	return scanner.Err()
}

// parseKeyValue splits a "key=value" or "key = value" line.
func parseKeyValue(line string) (key, value string, ok bool) {
	idx := strings.IndexByte(line, '=')
	if idx < 0 {
		return "", "", false
	}
	key = strings.TrimSpace(line[:idx])
	value = strings.TrimSpace(line[idx+1:])
	if key == "" {
		return "", "", false
	}
	return key, value, true
}

// setConfigField assigns value to the Config field identified by key.
func setConfigField(cfg *Config, key, value string) error {
	switch key {
	case "datadir":
		cfg.DataDir = value
	case "listen":
		cfg.ListenAddr = value
	case "rpc":
		cfg.RPCAddr = value
	case "network":
		cfg.Network = value
	case "maxpeers":
		n, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("config: invalid maxpeers value %q: %w", value, err)
		}
		cfg.MaxPeers = n
	case "mine":
		b, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("config: invalid mine value %q: %w", value, err)
		}
		cfg.MineEnabled = b
	case "loglevel":
		cfg.LogLevel = value
	case "logfile":
		cfg.LogFile = value
	default:
		// Unknown keys are silently ignored for forward compatibility.
	}
	return nil
}

// SaveConfig writes the configuration to the given path in key=value format.
func SaveConfig(path string, cfg Config) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("config: create directory %s: %w", dir, err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("config: create %s: %w", path, err)
	}

	w := bufio.NewWriter(f)
	if err := writeConfigFile(w, cfg); err != nil {
		_ = f.Close()
		return err
	}
	if err := w.Flush(); err != nil {
		_ = f.Close()
		return fmt.Errorf("config: flush %s: %w", path, err)
	}
	return f.Close()
}

// writeConfigFile writes a human-readable config file to w.
func writeConfigFile(w *bufio.Writer, cfg Config) error {
	lines := []string{
		"# Metanet Node Configuration\n",
		"# Generated by metanet init\n",
		"\n",
		fmt.Sprintf("datadir = %s\n", cfg.DataDir),
		fmt.Sprintf("listen = %s\n", cfg.ListenAddr),
		fmt.Sprintf("rpc = %s\n", cfg.RPCAddr),
		fmt.Sprintf("network = %s\n", cfg.Network),
		fmt.Sprintf("maxpeers = %d\n", cfg.MaxPeers),
		fmt.Sprintf("mine = %t\n", cfg.MineEnabled),
		fmt.Sprintf("loglevel = %s\n", cfg.LogLevel),
		fmt.Sprintf("logfile = %s\n", cfg.LogFile),
	}
	for _, line := range lines {
		if _, err := w.WriteString(line); err != nil {
			return fmt.Errorf("config: write: %w", err)
		}
	}
	return nil
}

// ConfigPath returns the path to the config file within the data directory.
func ConfigPath(dataDir string) string {
	return filepath.Join(dataDir, "config")
}
